###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123"
}

###
POST http://localhost:5000/webhook
Content-Type: application/json

{
  "MessageSid": "SM12345678egd90",
  "From": "+1234567890",
  "To": "+0987654321",
  "Body": "Test message",
  "NumMedia": "0"
}


###
POST https://ba53-202-55-188-85.ngrok-free.app/webhook
Content-Type: application/json

{
  "From": "+1234567890",
  "To": "+0987654321",
  "Body": "Test message"
}

###
GET https://92ad-202-55-188-85.ngrok-free.app/api/messages
Content-Type: application/json