
###
POST https://0be3-202-55-188-85.ngrok-free.app/api/messages/webhook
Content-Type: application/json

{
  "From": "+1234567890",
  "To": "+97696068185",
  "Body": "Test message"
}

###
GET http://localhost:3000/api/messages
Content-Type: application/json


###
POST https://92ad-202-55-188-85.ngrok-free.app/api/messages/send
Content-Type: application/json

 {
  "to": "+97699334270",
  "body": "Dangerous!!!",
 }


###
POST https://0be3-202-55-188-85.ngrok-free.app/api/messages/send
Content-Type: application/json

{
  "to": "+97696068185",
  "body": "Сэрэмжлүүлэг мессэжийг таньд илгээж байна.!"
}

###
POST https://766d-202-55-188-85.ngrok-free.app/api/messages/call
Content-Type: application/json

###
GET https://3cc4-202-126-89-122.ngrok-free.app/api/messages
Content-Type: application/json


###
GET https://3cc4-202-126-89-122.ngrok-free.app/api/allMes/all
Content-Type: application/json
